name: Python CI/CD

on:
  push:
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r dashboard/requirements.txt
          pip install -r pipeline/requirements.txt
          pip install -r pipeline/seed_master_data/requirements.txt
          pip install -r scheduler/requirements.txt
          pip install -r stop_trigger/requirements.txt

      - name: Run Pytest
        run: pytest -vv

  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r dashboard/requirements.txt
          pip install -r pipeline/requirements.txt
          pip install -r pipeline/seed_master_data/requirements.txt
          pip install -r scheduler/requirements.txt
          pip install -r stop_trigger/requirements.txt
          

      - name: Run Pylint
        run: pylint --fail-under=8 dashboard/*.py pipeline/*.py scheduler/*.py stop_trigger/*.py